AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: cloudformation-ankith-13072001
  EnableVersioning:
    Type: String
    AllowedValues: [Enabled, Suspended]
    Default: Enabled
    Description: Enable or disable versioning on the S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref EnableVersioning
